import type { SupabaseClient } from "@supabase/supabase-js";
import { attachOwnerProfileFields } from "../marketplace/attachOwnerProfileFields";
import { createSupabaseAdminClient } from "../supabase/admin";
import type { TrendingAdminRow } from "./admin-public-types";

export type { TrendingAdminRow } from "./admin-public-types";

export const TRENDING_LIMIT = 8;
/** In-app auto-generated listing thumbnails need at least this many weekly runs to trend */
const MIN_RUNS_AUTO_THUMBNAIL = 200;
const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

export type TrendingItem = {
  id: string;
  type: "workflow" | "prompt";
  edgaze_code: string | null;
  title: string | null;
  description: string | null;
  prompt_text: string | null;
  thumbnail_url: string | null;
  owner_id: string | null;
  owner_name: string | null;
  owner_handle: string | null;
  tags: string | null;
  monetisation_mode: string | null;
  is_paid: boolean | null;
  price_usd: number | null;
  view_count: number | null;
  like_count: number | null;
  created_at: string | null;
  published_at?: string | null;
  owner_avatar_url?: string | null;
  owner_is_verified_creator?: boolean | null;
  owner_is_verified?: boolean;
};

export type TrendingThisWeekResponse = {
  topWorkflowsThisWeek: TrendingItem[];
  topPromptsThisWeek: TrendingItem[];
};

export type TrendingAdminSnapshot = {
  trending_workflows: TrendingAdminRow[];
  trending_prompts: TrendingAdminRow[];
};

function eligibleForTrending(runs: number, thumbnailAutoGenerated: unknown): boolean {
  if (thumbnailAutoGenerated !== true) return true;
  return runs >= MIN_RUNS_AUTO_THUMBNAIL;
}

function toItem(row: Record<string, unknown>, type: "workflow" | "prompt"): TrendingItem {
  return {
    id: String(row.id ?? ""),
    type,
    edgaze_code: (row.edgaze_code as string) ?? null,
    title: (row.title as string) ?? null,
    description: (row.description as string) ?? null,
    prompt_text: (row.prompt_text as string) ?? null,
    thumbnail_url: (row.thumbnail_url as string) ?? null,
    owner_id: row.owner_id != null ? String(row.owner_id) : null,
    owner_name: (row.owner_name as string) ?? null,
    owner_handle: (row.owner_handle as string) ?? null,
    tags: (row.tags as string) ?? null,
    monetisation_mode: (row.monetisation_mode as string) ?? null,
    is_paid: (row.is_paid as boolean) ?? null,
    price_usd: row.price_usd != null ? Number(row.price_usd) : null,
    view_count:
      row.views_count != null
        ? Number(row.views_count)
        : row.view_count != null
          ? Number(row.view_count)
          : null,
    like_count:
      row.likes_count != null
        ? Number(row.likes_count)
        : row.like_count != null
          ? Number(row.like_count)
          : null,
    created_at: (row.created_at as string) ?? (row.published_at as string) ?? null,
    published_at: (row.published_at as string) ?? null,
  };
}

const baseSelectWorkflows = [
  "id",
  "owner_id",
  "type",
  "edgaze_code",
  "title",
  "description",
  "prompt_text",
  "thumbnail_url",
  "owner_name",
  "owner_handle",
  "tags",
  "monetisation_mode",
  "is_paid",
  "price_usd",
  "views_count",
  "likes_count",
  "created_at",
  "published_at",
  "thumbnail_auto_generated",
  "exclude_from_trending",
].join(",");

const baseSelectPrompts = [
  "id",
  "owner_id",
  "type",
  "edgaze_code",
  "title",
  "description",
  "prompt_text",
  "thumbnail_url",
  "owner_name",
  "owner_handle",
  "tags",
  "monetisation_mode",
  "is_paid",
  "price_usd",
  "views_count",
  "likes_count",
  "view_count",
  "like_count",
  "created_at",
  "thumbnail_auto_generated",
  "exclude_from_trending",
].join(",");

type ScoredWorkflow = {
  w: Record<string, unknown>;
  runs: number;
  views: number;
  likes: number;
};

type ScoredPrompt = {
  p: Record<string, unknown>;
  runs: number;
  views: number;
  likes: number;
};

async function loadScoredTrendingLists(supabase: SupabaseClient): Promise<{
  scoredWorkflows: ScoredWorkflow[];
  scoredPrompts: ScoredPrompt[];
}> {
  const since = new Date(Date.now() - WEEK_MS).toISOString();

  const { data: runRows } = await supabase
    .from("runs")
    .select("workflow_id, prompt_id, kind")
    .gte("started_at", since)
    .in("status", ["success", "error", "canceled"])
    .not("ended_at", "is", null);

  const workflowRunCounts = new Map<string, number>();
  const promptRunCounts = new Map<string, number>();
  for (const r of runRows ?? []) {
    const id =
      (r as { workflow_id?: string; prompt_id?: string }).workflow_id ??
      (r as { prompt_id?: string }).prompt_id;
    if (!id) continue;
    if ((r as { kind?: string }).kind === "workflow") {
      workflowRunCounts.set(id, (workflowRunCounts.get(id) ?? 0) + 1);
    } else {
      promptRunCounts.set(id, (promptRunCounts.get(id) ?? 0) + 1);
    }
  }

  const { data: viewEventRows } = await supabase
    .from("listing_view_events")
    .select("listing_type, listing_id")
    .gte("counted_at", since);

  const workflowViewWeek = new Map<string, number>();
  const promptViewWeek = new Map<string, number>();
  for (const v of viewEventRows ?? []) {
    const row = v as { listing_type?: string; listing_id?: string };
    const lid = row.listing_id;
    if (!lid) continue;
    if (row.listing_type === "workflow") {
      workflowViewWeek.set(lid, (workflowViewWeek.get(lid) ?? 0) + 1);
    } else if (row.listing_type === "prompt") {
      promptViewWeek.set(lid, (promptViewWeek.get(lid) ?? 0) + 1);
    }
  }

  let workflowsData: Record<string, unknown>[] = [];
  const wRes = await supabase
    .from("workflows")
    .select(baseSelectWorkflows)
    .eq("is_published", true)
    .is("removed_at", null)
    .in("visibility", ["public", "unlisted"]);

  if (wRes.error) {
    const msg = String((wRes.error as { message?: string })?.message ?? "").toLowerCase();
    if (msg.includes("visibility") || msg.includes("column")) {
      const fallback = await supabase
        .from("workflows")
        .select(baseSelectWorkflows)
        .eq("is_published", true)
        .eq("is_public", true)
        .is("removed_at", null);
      workflowsData = (fallback.data ?? []) as unknown as Record<string, unknown>[];
    } else {
      console.error("[trending] Workflows fetch error:", wRes.error);
    }
  } else {
    workflowsData = (wRes.data ?? []) as unknown as Record<string, unknown>[];
  }

  workflowsData = workflowsData.filter(
    (w) => !(w as { exclude_from_trending?: boolean }).exclude_from_trending,
  );

  const pRes = await supabase
    .from("prompts")
    .select(baseSelectPrompts)
    .in("type", ["prompt", "workflow"])
    .in("visibility", ["public", "unlisted"]);

  let promptsData = (pRes.data ?? []) as unknown as Record<string, unknown>[];
  if (pRes.error) {
    console.error("[trending] Prompts fetch error:", pRes.error);
  }

  promptsData = promptsData.filter(
    (p) => !(p as { exclude_from_trending?: boolean }).exclude_from_trending,
  );

  const promptOnly = promptsData.filter((p) => (p as { type?: string }).type !== "workflow");
  const workflowFromWorkflows = workflowsData.map((w: Record<string, unknown>) => ({
    ...w,
    type: "workflow",
  }));

  const scoredWorkflows = workflowFromWorkflows
    .map((w: Record<string, unknown>) => {
      const id = String(w.id ?? "");
      const runs = workflowRunCounts.get(id) ?? 0;
      const wk = workflowViewWeek.get(id) ?? 0;
      const views = wk > 0 ? wk : Number(w.views_count ?? 0);
      const likes = Number(w.likes_count ?? 0);
      return { w, runs, views, likes };
    })
    .filter(({ w, runs }) => eligibleForTrending(runs, w.thumbnail_auto_generated))
    .sort((a, b) => {
      if (b.runs !== a.runs) return b.runs - a.runs;
      if (b.views !== a.views) return b.views - a.views;
      return b.likes - a.likes;
    })
    .slice(0, TRENDING_LIMIT);

  const scoredPrompts = promptOnly
    .map((p) => {
      const id = String(p.id ?? "");
      const runs = promptRunCounts.get(id) ?? 0;
      const wk = promptViewWeek.get(id) ?? 0;
      const views =
        wk > 0 ? wk : Number((p as { views_count?: unknown }).views_count ?? p.view_count ?? 0);
      const likes = Number(p.likes_count ?? p.like_count ?? 0);
      return { p, runs, views, likes };
    })
    .filter(({ p, runs }) =>
      eligibleForTrending(
        runs,
        (p as { thumbnail_auto_generated?: unknown }).thumbnail_auto_generated,
      ),
    )
    .sort((a, b) => {
      if (b.runs !== a.runs) return b.runs - a.runs;
      if (b.views !== a.views) return b.views - a.views;
      return b.likes - a.likes;
    })
    .slice(0, TRENDING_LIMIT);

  return { scoredWorkflows, scoredPrompts };
}

function attachVerified(items: TrendingItem[]): TrendingItem[] {
  return items.map((it) => ({
    ...it,
    owner_is_verified: Boolean(it.owner_is_verified_creator),
  }));
}

function toAdminRow(
  item: TrendingItem,
  runs: number,
  weekViews: number,
  thumbAuto: unknown,
  excluded: unknown,
): TrendingAdminRow {
  return {
    ...item,
    weekly_runs: runs,
    week_views_for_rank: weekViews,
    thumbnail_auto_generated: typeof thumbAuto === "boolean" ? thumbAuto : null,
    exclude_from_trending: excluded === true,
  };
}

export async function computeTrendingThisWeek(): Promise<TrendingThisWeekResponse> {
  const supabase = createSupabaseAdminClient();
  const { scoredWorkflows, scoredPrompts } = await loadScoredTrendingLists(supabase);

  const topWorkflowsRaw = scoredWorkflows.map(({ w }) =>
    toItem(w as Record<string, unknown>, "workflow"),
  );
  const topPromptsRaw = scoredPrompts.map(({ p }) =>
    toItem(p as Record<string, unknown>, "prompt"),
  );

  await attachOwnerProfileFields(supabase, [...topWorkflowsRaw, ...topPromptsRaw]);

  return {
    topWorkflowsThisWeek: attachVerified(topWorkflowsRaw),
    topPromptsThisWeek: attachVerified(topPromptsRaw),
  };
}

export async function computeTrendingAdminSnapshot(): Promise<TrendingAdminSnapshot> {
  const supabase = createSupabaseAdminClient();
  const { scoredWorkflows, scoredPrompts } = await loadScoredTrendingLists(supabase);

  const topWorkflowsRaw = scoredWorkflows.map(({ w }) =>
    toItem(w as Record<string, unknown>, "workflow"),
  );
  const topPromptsRaw = scoredPrompts.map(({ p }) =>
    toItem(p as Record<string, unknown>, "prompt"),
  );

  await attachOwnerProfileFields(supabase, [...topWorkflowsRaw, ...topPromptsRaw]);

  const wfVerified = attachVerified(topWorkflowsRaw);
  const prVerified = attachVerified(topPromptsRaw);

  const trending_workflows = scoredWorkflows.map(({ w, runs, views }, i) => {
    const item = wfVerified[i];
    if (!item) throw new Error("[trending] workflow row mismatch");
    return toAdminRow(item, runs, views, w.thumbnail_auto_generated, w.exclude_from_trending);
  });

  const trending_prompts = scoredPrompts.map(({ p, runs, views }, i) => {
    const item = prVerified[i];
    if (!item) throw new Error("[trending] prompt row mismatch");
    return toAdminRow(item, runs, views, p.thumbnail_auto_generated, p.exclude_from_trending);
  });

  return { trending_workflows, trending_prompts };
}
