// src/components/prompt-studio/PublishPromptModal.tsx
"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import Image from "next/image";
import Link from "next/link";
import {
  X,
  Upload,
  Loader2,
  AlertTriangle,
  Sparkles,
  Link as LinkIcon,
  Copy,
  Download,
  CheckCircle2,
  RotateCcw,
  ChevronLeft,
  ChevronRight,
  BadgeDollarSign,
  Eye,
  FileText,
  Images,
  Lock,
} from "lucide-react";
import { useAuth } from "../auth/AuthContext";
import { uploadListingMedia } from "../../lib/creator-provisioning/upload-listing-media";
import {
  createImageObjectUrl,
  createSecureId,
  sanitizeImageSrc,
} from "../../lib/security/safe-values";
import VerifiedCreatorBadge from "../ui/VerifiedCreatorBadge";
import AssetPickerModalRaw from "../assets/AssetPickerModal";
import { createSupabaseBrowserClient } from "../../lib/supabase/browser";
import {
  PROMPT_MAX_USD,
  MIN_TRANSACTION_USD,
  validatePromptPrice,
} from "../../lib/marketplace/pricing";
import { PayoutSystemCard } from "../publish/PayoutSystemCard";

type PlaceholderDef = {
  name: string;
  question: string;
};

const AssetPickerModal = AssetPickerModalRaw as unknown as React.ComponentType<{
  onClose: () => void;
  onPick: (asset: any) => void;
}>;

type Visibility = "public" | "unlisted" | "private";
type MonetisationMode = "free" | "paywall";

type PublishMeta = {
  name: string;
  description: string;
  thumbnailUrl: string;
  /** True when the current thumbnail is from the in-app auto generator (not asset picker / upload). */
  thumbnailAutoGenerated?: boolean;
  tags: string;
  visibility: Visibility;
  paid: boolean;
  priceUsd: string;
  demoImageUrls?: string[];
};

type Props = {
  open: boolean;
  onClose: () => void;
  meta: PublishMeta;
  onMetaChange: (next: PublishMeta) => void;
  promptText: string;
  placeholders: PlaceholderDef[];
  editId?: string | null; // If provided, we're editing an existing prompt
  onPublished: () => void;
};

function cx(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

/**
 * Thumbnail prompt snippet: ONLY prompt text (no title/tags/price/etc) and blurred.
 */
function makePromptSnippetForThumb(full: string) {
  const cleaned = (full || "").replace(/\s+/g, " ").trim();
  if (!cleaned) return "";
  const pct = Math.max(40, Math.floor(cleaned.length * 0.18));
  const maxChars = Math.min(900, pct);
  const snippet = cleaned.slice(0, maxChars);
  return snippet + (cleaned.length > snippet.length ? "…" : "");
}

function wrapTextLines(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
  maxLines: number,
) {
  const words = (text || "").split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";

  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (ctx.measureText(test).width <= maxWidth) {
      line = test;
    } else {
      if (line) lines.push(line);
      line = w;
      if (lines.length >= maxLines - 1) break;
    }
  }
  if (line && lines.length < maxLines) lines.push(line);
  return lines;
}

function drawRoundedRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
) {
  const rr = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + rr, y);
  ctx.arcTo(x + w, y, x + w, y + h, rr);
  ctx.arcTo(x + w, y + h, x, y + h, rr);
  ctx.arcTo(x, y + h, x, y, rr);
  ctx.arcTo(x, y, x + w, y, rr);
  ctx.closePath();
}

/**
 * Create an auto thumbnail that contains ONLY blurred prompt text.
 * Important: Some browsers are flaky with ctx.filter; we include a manual blur fallback.
 */
async function createPromptOnlyThumbnail(promptText: string): Promise<string> {
  const W = 1280;
  const H = 800; // 16:10

  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas not supported");

  // Gradient backdrop
  const bg = ctx.createLinearGradient(0, 0, W, H);
  bg.addColorStop(0, "rgba(34, 211, 238, 1)");
  bg.addColorStop(1, "rgba(232, 121, 249, 1)");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  // Dark overlay
  ctx.fillStyle = "rgba(7, 8, 12, 0.76)";
  ctx.fillRect(0, 0, W, H);

  // Soft bloom
  const rg = ctx.createRadialGradient(W * 0.22, H * 0.22, 60, W * 0.22, H * 0.22, W * 0.9);
  rg.addColorStop(0, "rgba(34, 211, 238, 0.16)");
  rg.addColorStop(0.55, "rgba(232, 121, 249, 0.12)");
  rg.addColorStop(1, "rgba(0,0,0,0)");
  ctx.fillStyle = rg;
  ctx.fillRect(0, 0, W, H);

  // Inner card
  const pad = 46;
  const cardX = pad;
  const cardY = pad;
  const cardW = W - pad * 2;
  const cardH = H - pad * 2;

  ctx.save();
  ctx.shadowColor = "rgba(0,0,0,0.55)";
  ctx.shadowBlur = 42;
  ctx.shadowOffsetY = 18;
  ctx.fillStyle = "rgba(10, 11, 16, 0.72)";
  drawRoundedRect(ctx, cardX, cardY, cardW, cardH, 44);
  ctx.fill();
  ctx.restore();

  ctx.save();
  ctx.strokeStyle = "rgba(255,255,255,0.10)";
  ctx.lineWidth = 2;
  drawRoundedRect(ctx, cardX, cardY, cardW, cardH, 44);
  ctx.stroke();
  ctx.restore();

  const snippet = makePromptSnippetForThumb(promptText);
  if (!snippet) return canvas.toDataURL("image/png");

  const textAreaX = cardX + 70;
  const textAreaY = cardY + 90;
  const textAreaW = cardW - 140;
  const textAreaH = cardH - 180;

  const len = snippet.length;
  const fontSize = len <= 120 ? 58 : len <= 220 ? 46 : len <= 360 ? 38 : 32;
  const lineH = Math.round(fontSize * 1.24);

  // Render text to offscreen canvas
  const off = document.createElement("canvas");
  off.width = W;
  off.height = H;
  const octx = off.getContext("2d");
  if (!octx) throw new Error("Canvas not supported");

  octx.save();
  octx.font = `600 ${fontSize}px ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial`;
  octx.textBaseline = "top";
  octx.fillStyle = "rgba(255,255,255,0.92)";

  const maxLines = Math.max(5, Math.min(12, Math.floor(textAreaH / lineH)));
  const lines = wrapTextLines(octx, snippet, textAreaW, maxLines);

  const totalH = lines.length * lineH;
  let y = textAreaY + Math.max(0, Math.floor((textAreaH - totalH) * 0.35));
  for (const line of lines) {
    octx.fillText(line, textAreaX, y);
    y += lineH;
  }
  octx.restore();

  // Draw blurred text only
  ctx.save();
  const hasFilter = typeof (ctx as any).filter === "string";
  if (hasFilter) {
    (ctx as any).filter = "blur(18px)";
    ctx.globalAlpha = 0.95;
    ctx.drawImage(off, 0, 0);
  } else {
    // Manual blur fallback: layered jitter draws
    ctx.globalAlpha = 0.12;
    const radius = 10;
    for (let i = 0; i < 36; i++) {
      const dx = (Math.random() * 2 - 1) * radius;
      const dy = (Math.random() * 2 - 1) * radius;
      ctx.drawImage(off, dx, dy);
    }
    ctx.globalAlpha = 0.35;
    ctx.drawImage(off, 0, 0);
  }
  ctx.restore();

  // Extra veil to ensure unreadable
  ctx.save();
  const veil = ctx.createLinearGradient(
    textAreaX,
    textAreaY,
    textAreaX + textAreaW,
    textAreaY + textAreaH,
  );
  veil.addColorStop(0, "rgba(0,0,0,0.22)");
  veil.addColorStop(1, "rgba(0,0,0,0.14)");
  ctx.fillStyle = veil;
  drawRoundedRect(ctx, textAreaX - 18, textAreaY - 18, textAreaW + 36, textAreaH + 36, 28);
  ctx.fill();
  ctx.strokeStyle = "rgba(255,255,255,0.08)";
  ctx.lineWidth = 2;
  drawRoundedRect(ctx, textAreaX - 18, textAreaY - 18, textAreaW + 36, textAreaH + 36, 28);
  ctx.stroke();
  ctx.restore();

  return canvas.toDataURL("image/png");
}

function normalizeEdgazeCode(input: string) {
  return (input || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 32);
}

function baseCodeFromTitle(title: string) {
  const base = normalizeEdgazeCode(title || "");
  return base || "prompt";
}

function randomSuffix(len = 4) {
  return createSecureId("prompt", len).slice(-len).toLowerCase();
}

function safeArr(v: any): string[] {
  if (!v) return [];
  if (Array.isArray(v)) return v.map((x) => String(x)).filter(Boolean);
  return String(v)
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

async function withTimeout<T>(promise: Promise<T>, ms: number, label: string) {
  let t: any;
  const timeout = new Promise<T>((_, reject) => {
    t = setTimeout(() => reject(new Error(`${label} timed out`)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(t));
}

async function loadImage(src: string): Promise<HTMLImageElement> {
  return await new Promise((resolve, reject) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Failed to load image: ${src}`));
    img.src = src;
  });
}

async function qrDataUrlLocal(text: string): Promise<string> {
  try {
    const mod: any = await withTimeout(import("qrcode") as any, 2500, "QR module import");
    const QRCode = mod?.default ?? mod;
    const dataUrl = await withTimeout(
      QRCode.toDataURL(text, {
        errorCorrectionLevel: "H",
        margin: 1,
        scale: 10,
        color: { dark: "#0b0c10", light: "#ffffff" },
      }),
      4500,
      "QR generation",
    );
    return String(dataUrl);
  } catch {
    const controller = new AbortController();
    const kill = setTimeout(() => controller.abort(), 6000);
    try {
      const url = `https://api.qrserver.com/v1/create-qr-code/?size=900x900&data=${encodeURIComponent(text)}`;
      const res = await fetch(url, { signal: controller.signal });
      if (!res.ok) throw new Error("QR fetch failed");
      const blob = await res.blob();
      return await new Promise<string>((resolve, reject) => {
        const r = new FileReader();
        r.onload = () => resolve(String(r.result));
        r.onerror = () => reject(new Error("Failed to read QR blob"));
        r.readAsDataURL(blob);
      });
    } finally {
      clearTimeout(kill);
    }
  }
}

async function qrWithCenteredLogoDataUrl(text: string) {
  const qrDataUrl = await qrDataUrlLocal(text);

  const canvas = document.createElement("canvas");
  canvas.width = 900;
  canvas.height = 900;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas not supported");

  const qrImg = await loadImage(qrDataUrl);
  ctx.drawImage(qrImg, 0, 0, 900, 900);

  const badgeSize = 200;
  const badgeX = (900 - badgeSize) / 2;
  const badgeY = (900 - badgeSize) / 2;

  ctx.save();
  ctx.shadowColor = "rgba(0,0,0,0.25)";
  ctx.shadowBlur = 18;
  ctx.fillStyle = "rgba(255,255,255,0.96)";
  const r = 36;
  ctx.beginPath();
  ctx.moveTo(badgeX + r, badgeY);
  ctx.arcTo(badgeX + badgeSize, badgeY, badgeX + badgeSize, badgeY + badgeSize, r);
  ctx.arcTo(badgeX + badgeSize, badgeY + badgeSize, badgeX, badgeY + badgeSize, r);
  ctx.arcTo(badgeX, badgeY + badgeSize, badgeX, badgeY, r);
  ctx.arcTo(badgeX, badgeY, badgeX + badgeSize, badgeY, r);
  ctx.closePath();
  ctx.fill();
  ctx.restore();

  try {
    const logo = await withTimeout(loadImage("/brand/edgaze-mark.png"), 2500, "Logo load");
    const logoSize = 120;
    ctx.drawImage(logo, (900 - logoSize) / 2, (900 - logoSize) / 2, logoSize, logoSize);
  } catch {
    // ignore
  }

  return canvas.toDataURL("image/png");
}

function ConfettiSides({ active }: { active: boolean }) {
  const [pieceStyles, setPieceStyles] = useState<Array<Record<string, string>>>([]);

  useEffect(() => {
    queueMicrotask(() => {
      setPieceStyles(
        new Array(18).fill(null).map((_, i) => {
          const left = i % 2 === 0;
          const x = left ? Math.random() * 18 : 82 + Math.random() * 18;
          const delay = Math.random() * 0.2;
          const size = 8 + Math.random() * 10;
          return {
            left: `${x}%`,
            top: "-10%",
            width: `${size}px`,
            height: `${size * 1.55}px`,
            animationDelay: `${delay}s`,
          };
        }),
      );
    });
  }, []);

  if (!active) return null;

  return (
    <div className="pointer-events-none absolute inset-0 z-20 overflow-hidden">
      {pieceStyles.length > 0 &&
        pieceStyles.map((style, i) => <div key={i} className="confetti" style={style} />)}
      <style jsx>{`
        .confetti {
          position: absolute;
          border-radius: 3px;
          opacity: 0.95;
          background: linear-gradient(90deg, rgba(34, 211, 238, 1), rgba(232, 121, 249, 1));
          animation: fall 1.05s cubic-bezier(0.12, 0.6, 0.2, 1) forwards;
        }
        @keyframes fall {
          0% {
            transform: translateY(0) rotate(0deg);
            opacity: 0.95;
          }
          100% {
            transform: translateY(125vh) rotate(520deg);
            opacity: 0;
          }
        }
      `}</style>
    </div>
  );
}

/**
 * Prompt preview snippet for REVIEW (display only).
 * Keep it short, and we'll blur it heavily in UI.
 */
function makePromptPreviewForUI(text: string) {
  const cleaned = (text || "").replace(/\s+/g, " ").trim();
  if (!cleaned) return "";
  const maxChars = Math.min(520, Math.max(160, Math.floor(cleaned.length * 0.12)));
  const snippet = cleaned.slice(0, maxChars);
  return snippet + (cleaned.length > snippet.length ? "…" : "");
}

type StepKey = "details" | "pricing" | "media" | "visibility" | "review";

const STEPS: Array<{
  key: StepKey;
  title: string;
  desc: string;
  icon: React.ComponentType<{ className?: string }>;
}> = [
  { key: "details", title: "Basics", desc: "Title, description, tags, code.", icon: FileText },
  {
    key: "pricing",
    title: "Pricing",
    desc: "Free or set a price ($3-$50).",
    icon: BadgeDollarSign,
  },
  { key: "media", title: "Media", desc: "Thumbnail + optional demos.", icon: Images },
  { key: "visibility", title: "Visibility", desc: "Public.", icon: Lock },
  { key: "review", title: "Review", desc: "Confirm and publish.", icon: Eye },
];

function StepDot({
  index,
  title,
  desc,
  active,
  done,
  canClick,
  icon: Icon,
  onClick,
}: {
  index: number;
  title: string;
  desc: string;
  active: boolean;
  done: boolean;
  canClick: boolean;
  icon: React.ComponentType<{ className?: string }>;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={canClick ? onClick : undefined}
      className={cx(
        "group flex items-center gap-3 rounded-2xl px-3 py-2 text-left transition-all duration-200",
        canClick ? "hover:bg-white/[0.04]" : "opacity-80",
        active &&
          "bg-[linear-gradient(180deg,rgba(34,211,238,0.14),rgba(255,255,255,0.04))] shadow-[0_12px_32px_rgba(6,182,212,0.12)]",
      )}
    >
      <div
        className={cx(
          "grid h-10 w-10 place-items-center rounded-full border text-[11px] font-semibold",
          done
            ? "border-cyan-400/30 bg-cyan-400/10 text-cyan-200"
            : active
              ? "border-cyan-300/35 bg-cyan-300/15 text-white"
              : "border-white/12 bg-white/[0.03] text-white/80",
        )}
      >
        {done ? <CheckCircle2 className="h-4 w-4" /> : <Icon className="h-4 w-4" />}
      </div>
      <div className="min-w-0">
        <div className={cx("text-[11px] font-semibold", active ? "text-white" : "text-white/85")}>
          {title}
        </div>
        <div className="text-[10px] text-white/45 truncate">
          {done ? `Step ${index + 1}` : desc}
        </div>
      </div>
    </button>
  );
}

function MobileStepPill({
  active,
  done,
  title,
  icon: Icon,
  canClick,
  onClick,
}: {
  active: boolean;
  done: boolean;
  title: string;
  icon: React.ComponentType<{ className?: string }>;
  canClick: boolean;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={canClick ? onClick : undefined}
      className={cx(
        "group flex min-w-0 flex-1 flex-col items-center gap-1.5 text-center",
        !canClick && "opacity-70",
      )}
    >
      <div
        className={cx(
          "grid h-11 w-11 place-items-center rounded-full border transition-all duration-200",
          done
            ? "border-cyan-300/35 bg-[radial-gradient(circle_at_top,rgba(34,211,238,0.38),rgba(9,14,24,0.96)_72%)] text-cyan-50 shadow-[0_10px_24px_rgba(34,211,238,0.18)]"
            : active
              ? "border-white/18 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.18),rgba(9,14,24,0.96)_72%)] text-white shadow-[0_10px_24px_rgba(255,255,255,0.08)]"
              : "border-white/10 bg-[radial-gradient(circle_at_top,rgba(255,255,255,0.08),rgba(9,14,24,0.96)_72%)] text-white/70 group-hover:border-white/20 group-hover:text-white/90",
        )}
      >
        {done ? <CheckCircle2 className="h-4 w-4" /> : <Icon className="h-4 w-4" />}
      </div>
      <div
        className={cx(
          "text-[9px] font-medium tracking-[0.02em]",
          active ? "text-white" : "text-white/58",
        )}
      >
        {title}
      </div>
    </button>
  );
}

export default function PublishPromptModal({
  open,
  onClose,
  meta,
  onMetaChange,
  promptText,
  placeholders,
  editId,
  onPublished,
}: Props) {
  const { userId, workspaceUserId, profile, requireAuth, getAccessToken } = useAuth();
  const listingOwnerId = workspaceUserId ?? userId;
  const supabase = useMemo(() => createSupabaseBrowserClient(), []);

  // Guided step (0..4)
  const [step, setStep] = useState<number>(0);
  const [completed, setCompleted] = useState<Record<StepKey, boolean>>({
    details: false,
    pricing: false,
    media: false,
    visibility: false,
    review: false,
  });

  // Fields
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [tagsInput, setTagsInput] = useState("");

  const [visibility, setVisibility] = useState<Visibility>("public");
  const [monetisationMode, setMonetisationMode] = useState<MonetisationMode>("free");
  const [priceUsd, setPriceUsd] = useState<string>("2.99");

  const [edgazeCode, setEdgazeCode] = useState<string>("");

  const [codeStatus, setCodeStatus] = useState<
    "idle" | "checking" | "available" | "taken" | "invalid"
  >("idle");
  const [codeMsg, setCodeMsg] = useState<string>("");

  const codeDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null);
  const [autoThumbFile, setAutoThumbFile] = useState<File | null>(null);
  const [autoThumbDataUrl, setAutoThumbDataUrl] = useState<string | null>(null);
  const [autoThumbBusy, setAutoThumbBusy] = useState(false);

  const [demoFiles, setDemoFiles] = useState<(File | null)[]>(new Array(6).fill(null));
  const [demoUrlsPicked, setDemoUrlsPicked] = useState<string[]>([]);

  const [assetPickerOpen, setAssetPickerOpen] = useState(false);

  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const [published, setPublished] = useState(false);
  const [publishedCode, setPublishedCode] = useState("");
  const [publishedUrl, setPublishedUrl] = useState("");
  const [acceptedCreatorTerms, setAcceptedCreatorTerms] = useState(false);

  const [confetti, setConfetti] = useState(false);

  const [qrBusy, setQrBusy] = useState(false);
  const [qrErr, setQrErr] = useState<string | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);

  const [parentNotified, setParentNotified] = useState(false);
  const [isMobileViewport, setIsMobileViewport] = useState(false);
  const [mobileActiveStep, setMobileActiveStep] = useState<StepKey>("details");
  const uploadedThumbnailPreviewUrl = useMemo(
    () => createImageObjectUrl(thumbnailFile),
    [thumbnailFile],
  );
  const contentScrollRef = useRef<HTMLDivElement | null>(null);
  const sectionRefs = useRef<Record<StepKey, HTMLDivElement | null>>({
    details: null,
    pricing: null,
    media: null,
    visibility: null,
    review: null,
  });
  const safeThumbnailSrc = sanitizeImageSrc(meta?.thumbnailUrl);
  const safeUploadedThumbnailSrc = sanitizeImageSrc(uploadedThumbnailPreviewUrl);
  const safeAutoThumbnailSrc = sanitizeImageSrc(autoThumbDataUrl);

  useEffect(() => {
    return () => {
      if (uploadedThumbnailPreviewUrl?.startsWith("blob:")) {
        URL.revokeObjectURL(uploadedThumbnailPreviewUrl);
      }
    };
  }, [uploadedThumbnailPreviewUrl]);

  const canReceivePayments = Boolean((profile as any)?.can_receive_payments);
  const ownerName = (profile as any)?.full_name || "Creator";
  const ownerHandle = (profile as any)?.handle || "creator";

  const safeTitle = (title || "").trim();
  const safeDescription = (description || "").trim();

  const demoCount = demoUrlsPicked.filter(Boolean).length + demoFiles.filter((f) => !!f).length;

  const hasValidPlaceholders = placeholders.every(
    (p) => (p.name || "").trim() && (p.question || "").trim(),
  );

  const isDetailsValid =
    safeTitle.length > 0 &&
    safeDescription.length > 0 &&
    normalizeEdgazeCode(edgazeCode).length >= 3 &&
    promptText.trim().length > 0 &&
    hasValidPlaceholders;

  const priceNum = monetisationMode === "paywall" ? Number(priceUsd) || 0 : 0;
  const priceValidation =
    monetisationMode === "paywall" ? validatePromptPrice(priceNum) : { valid: true };
  const isPricingValid =
    monetisationMode === "free" || (monetisationMode === "paywall" && priceValidation.valid);

  // Media: demo images optional during beta
  const isMediaValid = true;

  // Visibility: only public enabled during beta
  const isVisibilityValid = visibility === "public";

  const needsTermsAcceptance = monetisationMode === "paywall" && !canReceivePayments;
  const isReviewValid =
    isDetailsValid &&
    isPricingValid &&
    isMediaValid &&
    isVisibilityValid &&
    (!needsTermsAcceptance || acceptedCreatorTerms);

  const canPublish = !busy && !!listingOwnerId && codeStatus === "available" && isReviewValid;

  useEffect(() => {
    if (typeof window === "undefined") return;
    const mediaQuery = window.matchMedia("(max-width: 767px)");
    const sync = () => setIsMobileViewport(mediaQuery.matches);
    sync();
    mediaQuery.addEventListener("change", sync);
    return () => mediaQuery.removeEventListener("change", sync);
  }, []);

  useEffect(() => {
    if (!open) return;

    setPublished(false);
    setPublishedCode("");
    setPublishedUrl("");
    setMobileActiveStep("details");
    setParentNotified(false);
    setAcceptedCreatorTerms(false);
    setErr(null);
    setBusy(false);
    setQrBusy(false);
    setQrErr(null);
    setQrDataUrl(null);

    // seed from meta
    setTitle(meta?.name || "");
    setDescription(meta?.description || "");
    setTagsInput(meta?.tags || "");
    setVisibility(meta?.visibility || "public");
    setMonetisationMode("free");
    setPriceUsd(meta?.priceUsd || "2.99");

    // Use existing code when editing, otherwise generate from title
    if (editId && (meta as any)?.edgazeCode) {
      setEdgazeCode((meta as any).edgazeCode);
    } else {
      const base = baseCodeFromTitle(meta?.name || "");
      setEdgazeCode(base);
    }

    // reset files
    setThumbnailFile(null);
    setAutoThumbFile(null);
    setAutoThumbDataUrl(null);
    setDemoFiles(new Array(6).fill(null));
    setDemoUrlsPicked(safeArr(meta?.demoImageUrls));
    if (contentScrollRef.current) contentScrollRef.current.scrollTop = 0;

    // step
    setStep(0);
    setCompleted({
      details: false,
      pricing: false,
      media: false,
      visibility: false,
      review: false,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // keep parent meta in sync (lightly)
  useEffect(() => {
    if (!open) return;
    onMetaChange?.({
      ...meta,
      name: title,
      description,
      tags: tagsInput,
      visibility,
      paid: false,
      priceUsd,
      demoImageUrls: demoUrlsPicked,
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, title, description, tagsInput, visibility, priceUsd, demoUrlsPicked]);

  function closeNow() {
    if (busy) return;
    onClose();
  }

  async function checkCodeAvailability(code: string) {
    const c = normalizeEdgazeCode(code);
    if (!c || c.length < 3) {
      setCodeStatus("invalid");
      setCodeMsg("Too short.");
      return;
    }

    setCodeStatus("checking");
    setCodeMsg("Checking…");

    const { data, error } = await supabase
      .from("prompts")
      .select("id")
      .eq("edgaze_code", c)
      .limit(1);

    if (error) {
      setCodeStatus("idle");
      setCodeMsg("Could not check.");
      return;
    }

    // If editing, exclude the current prompt from the check
    const taken =
      Array.isArray(data) &&
      data.length > 0 &&
      (!editId || !data.some((row: any) => row.id === editId));
    setCodeStatus(taken ? "taken" : "available");
    setCodeMsg(taken ? "Taken" : "Available");
  }

  useEffect(() => {
    if (!open) return;

    if (codeDebounceRef.current) clearTimeout(codeDebounceRef.current);

    const c = normalizeEdgazeCode(edgazeCode);
    if (!c) {
      setCodeStatus("invalid");
      setCodeMsg("Invalid.");
      return;
    }

    codeDebounceRef.current = setTimeout(() => {
      checkCodeAvailability(c);
    }, 420);

    return () => {
      if (codeDebounceRef.current) clearTimeout(codeDebounceRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [edgazeCode, open]);

  async function ensureAvailableCodeOrAutofix(): Promise<string | null> {
    const base = normalizeEdgazeCode(edgazeCode);
    if (!base) return null;

    const { data } = await supabase.from("prompts").select("id").eq("edgaze_code", base).limit(1);
    // If editing, exclude the current prompt from the check
    const taken =
      data && data.length > 0 && (!editId || !data.some((row: any) => row.id === editId));
    if (!taken) {
      setCodeStatus("available");
      setCodeMsg("Available");
      setEdgazeCode(base);
      return base;
    }

    for (let i = 0; i < 6; i++) {
      const next = `${base}-${randomSuffix(4)}`.slice(0, 32);
      const { data: d2 } = await supabase
        .from("prompts")
        .select("id")
        .eq("edgaze_code", next)
        .limit(1);
      const taken2 = d2 && d2.length > 0 && (!editId || !d2.some((row: any) => row.id === editId));
      if (!taken2) {
        setCodeStatus("available");
        setCodeMsg("Available");
        setEdgazeCode(next);
        return next;
      }
    }

    setCodeStatus("taken");
    setCodeMsg("Pick another.");
    return null;
  }

  async function generateAutoThumbnail() {
    setAutoThumbBusy(true);
    try {
      const dataUrl = await createPromptOnlyThumbnail(promptText);
      setAutoThumbDataUrl(dataUrl);

      const res = await fetch(dataUrl);
      const blob = await res.blob();
      const f = new File([blob], "auto-thumbnail.png", { type: "image/png" });
      setAutoThumbFile(f);
    } catch {
      setAutoThumbDataUrl(null);
      setAutoThumbFile(null);
    } finally {
      setAutoThumbBusy(false);
    }
  }

  // Generate auto thumbnail on open (if none selected/uploaded)
  useEffect(() => {
    if (!open) return;
    if (!meta?.thumbnailUrl && !thumbnailFile && !autoThumbFile) {
      generateAutoThumbnail().catch(() => {});
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  // Keep auto thumbnail in sync with prompt edits (instant-ish), unless user provided custom thumbnail (upload or asset)
  useEffect(() => {
    if (!open) return;
    if (meta?.thumbnailUrl) return; // asset chosen
    if (thumbnailFile) return; // user upload
    const t = setTimeout(() => {
      generateAutoThumbnail().catch(() => {});
    }, 420);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [promptText, open, meta?.thumbnailUrl, thumbnailFile]);

  async function copyToClipboard(text: string) {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.left = "-9999px";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
    }
  }

  async function downloadDataUrl(dataUrl: string, filename: string) {
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
  }

  async function generateQrAndUpload(opts: { url: string; promptId: string }) {
    setQrErr(null);
    setQrBusy(true);
    try {
      const qr = await withTimeout(qrWithCenteredLogoDataUrl(opts.url), 9000, "QR render");
      setQrDataUrl(qr);

      try {
        const blob = await (await fetch(qr)).blob();
        const qrFile = new File([blob], `edgaze-qr-${normalizeEdgazeCode(edgazeCode)}.png`, {
          type: "image/png",
        });
        await withTimeout(
          uploadListingMedia({
            getAccessToken,
            listingType: "prompt",
            resourceId: opts.promptId,
            kind: "qr",
            file: qrFile,
          }),
          9000,
          "QR upload",
        );
      } catch {
        // ignore upload failures
      }
    } catch (e: any) {
      setQrErr(e?.message || "QR generation failed.");
      setQrDataUrl(null);
    } finally {
      setQrBusy(false);
    }
  }

  function markCompletedForCurrentStep() {
    const key = STEPS[step]?.key;
    if (!key) return;
    setCompleted((prev) => ({ ...prev, [key]: true }));
  }

  function stepCanAdvance(fromStep: number) {
    const key = STEPS[fromStep]?.key;
    if (!key) return false;
    if (key === "details") return isDetailsValid && codeStatus === "available";
    if (key === "pricing") return isPricingValid;
    if (key === "media") return isMediaValid;
    if (key === "visibility") return isVisibilityValid;
    if (key === "review") return isReviewValid;
    return false;
  }

  async function goNext() {
    setErr(null);

    // Step-specific validations + nicer error routing
    const key = STEPS[step]?.key;

    if (key === "details") {
      if (!safeTitle) return setErr("Add a title.");
      if (!safeDescription) return setErr("Add a description.");
      if (!promptText.trim()) return setErr("Prompt text is empty.");
      if (!hasValidPlaceholders) return setErr("Fix placeholder fields before publishing.");
      const c = normalizeEdgazeCode(edgazeCode);
      if (!c || c.length < 3) return setErr("Edgaze code is too short.");
      if (codeStatus === "taken") return setErr("That Edgaze code is taken.");
      if (codeStatus !== "available") return setErr("Wait for the Edgaze code check to finish.");
    }

    // Media: demo images are optional during beta

    if (key === "pricing") {
      if (monetisationMode === "paywall" && !priceValidation.valid) {
        return setErr(priceValidation.error || "Invalid price.");
      }
    }

    if (key === "visibility") {
      if (visibility !== "public") return setErr("Only Public is available.");
    }

    // mark as completed if it is valid
    if (stepCanAdvance(step)) markCompletedForCurrentStep();

    setStep((s) => Math.min(s + 1, STEPS.length - 1));
  }

  function goPrev() {
    setErr(null);
    setStep((s) => Math.max(s - 1, 0));
  }

  function goToStep(index: number) {
    // allow clicking back anytime; forward only if previous steps are valid/completed
    if (index <= step) return setStep(index);

    // can jump forward only if all prior steps are valid
    for (let i = 0; i < index; i++) {
      if (!stepCanAdvance(i)) return;
    }
    setStep(index);
  }

  async function handlePublish() {
    setErr(null);

    if (!requireAuth() || !listingOwnerId) {
      setErr("You must be signed in to publish.");
      return;
    }

    if (!isReviewValid) {
      setErr("Complete all steps before publishing.");
      return;
    }

    setBusy(true);

    try {
      let finalCode = normalizeEdgazeCode(edgazeCode);
      if (!finalCode) {
        setErr("Edgaze code is invalid.");
        setBusy(false);
        return;
      }

      if (codeStatus !== "available") {
        const fixed = await ensureAvailableCodeOrAutofix();
        if (!fixed) {
          setErr("Pick a unique Edgaze code.");
          setBusy(false);
          return;
        }
        finalCode = fixed;
      }

      const effectiveMonetisation: MonetisationMode =
        monetisationMode === "paywall" ? "paywall" : "free";
      const effectivePrice =
        effectiveMonetisation === "paywall"
          ? (() => {
              const v = validatePromptPrice(Number(priceUsd) || 0);
              if (!v.valid) throw new Error(v.error);
              return Number(priceUsd) || MIN_TRANSACTION_USD;
            })()
          : 0;

      const cleanTags = safeArr(tagsInput);

      let promptId: string;

      if (editId) {
        // Update existing prompt
        promptId = editId;

        const updateRow: any = {
          title: safeTitle,
          description: safeDescription,
          prompt_text: promptText, // FULL prompt
          placeholders,

          tags: cleanTags.join(","),
          visibility,
          monetisation_mode: effectiveMonetisation,
          is_paid: effectiveMonetisation === "paywall",
          price_usd: effectivePrice,

          edgaze_code: finalCode,

          is_published: true,
          is_public: true,
          updated_at: new Date().toISOString(),
        };

        const { error: updateErr } = await supabase
          .from("prompts")
          .update(updateRow)
          .eq("id", editId);
        if (updateErr) throw updateErr;
      } else {
        // Create new prompt
        const insertRow: any = {
          owner_id: listingOwnerId,
          owner_name: ownerName,
          owner_handle: ownerHandle,

          type: "prompt",
          title: safeTitle,
          description: safeDescription,
          prompt_text: promptText, // FULL prompt
          placeholders,

          tags: cleanTags.join(","),
          visibility,
          monetisation_mode: effectiveMonetisation,
          is_paid: effectiveMonetisation === "paywall",
          price_usd: effectivePrice,

          edgaze_code: finalCode,

          is_published: true,
          is_public: true,

          views_count: 0,
          likes_count: 0,
          runs_count: 0,

          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        };

        const { data: created, error: createErr } = await supabase
          .from("prompts")
          .insert(insertRow)
          .select("id")
          .single();
        if (createErr) throw createErr;

        promptId = created?.id as string;
        if (!promptId) throw new Error("Prompt created but ID missing.");
      }

      let thumbnailUrl: string | null = null;
      let thumbnailAutoGenerated = false;

      const metaThumb = String(meta.thumbnailUrl || "").trim();
      if (metaThumb) {
        thumbnailUrl = metaThumb;
        thumbnailAutoGenerated = meta.thumbnailAutoGenerated === true;
      } else if (thumbnailFile || autoThumbFile) {
        if (!thumbnailFile && !autoThumbFile) {
          await generateAutoThumbnail();
        }
        const thumbToUpload = thumbnailFile ?? autoThumbFile;
        if (thumbToUpload) {
          const up = await uploadListingMedia({
            getAccessToken,
            listingType: "prompt",
            resourceId: promptId,
            kind: "thumbnail",
            file: thumbToUpload,
          });
          thumbnailUrl = up.publicUrl || null;
          thumbnailAutoGenerated = !thumbnailFile;
        }
      } else if (editId) {
        thumbnailUrl = meta.thumbnailUrl?.trim() || null;
        thumbnailAutoGenerated = meta.thumbnailAutoGenerated === true;
      }

      const demoUrls: string[] = [];
      const seenUrls = new Set<string>();

      // Add picked URLs (these come from asset picker or existing demos when editing)
      for (const u of demoUrlsPicked) {
        if (u && !seenUrls.has(u)) {
          demoUrls.push(u);
          seenUrls.add(u);
        }
      }

      // Preserve existing demo URLs when editing (if not already added)
      if (editId && meta?.demoImageUrls) {
        for (const u of meta.demoImageUrls) {
          if (u && !seenUrls.has(u)) {
            demoUrls.push(u);
            seenUrls.add(u);
          }
        }
      }

      // Upload new demo files
      for (let i = 0; i < demoFiles.length; i++) {
        const f = demoFiles[i];
        if (!f) continue;
        const up = await uploadListingMedia({
          getAccessToken,
          listingType: "prompt",
          resourceId: promptId,
          kind: "demo",
          index: i,
          file: f,
        });
        if (up.publicUrl) demoUrls.push(up.publicUrl);
      }

      const demoFinal = demoUrls.filter(Boolean).slice(0, 6);

      // When editing, merge media updates into the main update
      if (editId) {
        const mediaPatch: any = {
          thumbnail_url: thumbnailUrl,
          thumbnail_auto_generated: thumbnailAutoGenerated,
          demo_images: demoFinal.length ? demoFinal : null,
          output_demo_urls: demoFinal.length ? demoFinal : null,
          updated_at: new Date().toISOString(),
        };
        const { error: patchErr } = await supabase
          .from("prompts")
          .update(mediaPatch)
          .eq("id", promptId);
        if (patchErr) throw patchErr;
      } else {
        // For new prompts, update media separately
        const patch: any = {
          thumbnail_url: thumbnailUrl,
          thumbnail_auto_generated: thumbnailAutoGenerated,
          demo_images: demoFinal.length ? demoFinal : null,
          output_demo_urls: demoFinal.length ? demoFinal : null,
          updated_at: new Date().toISOString(),
        };
        const { error: patchErr } = await supabase.from("prompts").update(patch).eq("id", promptId);
        if (patchErr) throw patchErr;
      }

      // Use current origin (works for localhost and production)
      const origin = typeof window !== "undefined" ? window.location.origin : "https://edgaze.ai";
      const url = `${origin}/p/${ownerHandle}/${finalCode}`;

      setPublishedCode(finalCode);
      setPublishedUrl(url);
      setPublished(true);

      setConfetti(true);
      setTimeout(() => setConfetti(false), 1200);

      await generateQrAndUpload({ url, promptId });

      setCompleted((c) => ({ ...c, review: true }));
      // do NOT auto-close
    } catch (e: any) {
      setErr(e?.message || "Publish failed.");
    } finally {
      setBusy(false);
    }
  }

  function handleDone() {
    if (!parentNotified) {
      try {
        onPublished?.();
      } catch {
        // ignore
      }
      setParentNotified(true);
    }
    onClose();
  }

  const stepKey = STEPS[step]?.key;
  const showAllMobileSections = isMobileViewport && !published;
  const activeVisibleStep = showAllMobileSections ? mobileActiveStep : stepKey;
  const mobileSpyOffset = 28;

  function scrollToPromptSection(nextStep: StepKey) {
    setMobileActiveStep(nextStep);
    const index = STEPS.findIndex((item) => item.key === nextStep);
    if (index >= 0) setStep(index);
    const root = contentScrollRef.current;
    const node = sectionRefs.current[nextStep];
    if (!node || !root) return;
    const nextTop = Math.max(0, node.offsetTop - mobileSpyOffset);
    root.scrollTo({ top: nextTop, behavior: "smooth" });
  }

  useEffect(() => {
    if (!open) return;
    if (!showAllMobileSections) return;
    const root = contentScrollRef.current;
    if (!root) return;

    const entries = Object.entries(sectionRefs.current).filter(([, node]) => !!node) as Array<
      [StepKey, HTMLDivElement]
    >;
    if (!entries.length) return;

    let rafId = 0;

    const syncActiveStep = () => {
      const scrollTop = root.scrollTop + mobileSpyOffset + 8;
      const isNearBottom = root.scrollTop + root.clientHeight >= root.scrollHeight - 24;
      let nextStep = entries[0][0];

      if (isNearBottom) {
        nextStep = entries[entries.length - 1][0];
      } else {
        for (const [key, node] of entries) {
          if (node.offsetTop <= scrollTop) {
            nextStep = key;
          } else {
            break;
          }
        }
      }

      setMobileActiveStep((prev) => (prev === nextStep ? prev : nextStep));
      const index = STEPS.findIndex((item) => item.key === nextStep);
      if (index >= 0) {
        setStep((prev) => (prev === index ? prev : index));
      }
    };

    const handleScroll = () => {
      cancelAnimationFrame(rafId);
      rafId = window.requestAnimationFrame(syncActiveStep);
    };

    syncActiveStep();
    root.addEventListener("scroll", handleScroll, { passive: true });
    window.addEventListener("resize", handleScroll);

    return () => {
      cancelAnimationFrame(rafId);
      root.removeEventListener("scroll", handleScroll);
      window.removeEventListener("resize", handleScroll);
    };
  }, [open, showAllMobileSections]);

  if (!open) return null;

  const headerCta = !published ? (
    <button
      onClick={
        showAllMobileSections ? handlePublish : stepKey === "review" ? handlePublish : goNext
      }
      disabled={
        published
          ? true
          : showAllMobileSections
            ? !canPublish
            : stepKey === "review"
              ? !canPublish
              : !stepCanAdvance(step)
      }
      className={cx(
        "inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[11px] font-semibold",
        "bg-white text-black hover:bg-white/90 transition-colors",
        (showAllMobileSections
          ? !canPublish
          : stepKey === "review"
            ? !canPublish
            : !stepCanAdvance(step)) && "opacity-60 cursor-not-allowed",
      )}
    >
      {busy ? (
        <>
          <Loader2 className="h-4 w-4 animate-spin" />
          {editId ? "Updating…" : "Publishing…"}
        </>
      ) : showAllMobileSections || stepKey === "review" ? (
        <>
          <Sparkles className="h-4 w-4" />
          {editId ? "Update" : "Publish"}
        </>
      ) : (
        <>
          <ChevronRight className="h-4 w-4" />
          Next
        </>
      )}
    </button>
  ) : (
    <button
      onClick={handleDone}
      className="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[11px] font-semibold bg-white text-black hover:bg-white/90 transition-colors"
    >
      Done
    </button>
  );

  const shell = (
    <div className="fixed inset-0 z-[200]">
      <div className="absolute inset-0 bg-black/80" onClick={published ? undefined : closeNow} />

      <div className="absolute inset-0 flex items-center justify-center p-0 sm:p-4">
        <div
          className="relative flex h-[100dvh] w-full flex-col overflow-hidden border-y border-white/10 bg-[#0b0c10] shadow-[0_40px_160px_rgba(0,0,0,0.75)] sm:h-[min(620px,88vh)] sm:max-h-[92vh] sm:w-[min(900px,96vw)] sm:rounded-2xl sm:border"
          style={{
            paddingTop: "max(env(safe-area-inset-top), 12px)",
            paddingBottom: "max(env(safe-area-inset-bottom), 16px)",
          }}
        >
          <ConfettiSides active={confetti} />

          {/* Header */}
          <div className="shrink-0 border-b border-white/10 px-4 py-2.5 sm:flex sm:h-[56px] sm:items-center sm:justify-between sm:px-5 sm:py-0">
            <div className="flex items-center gap-2 sm:gap-3 min-w-0">
              <Image
                src="/brand/edgaze-mark.png"
                alt="Edgaze"
                width={28}
                height={28}
                className="h-7 w-7 shrink-0"
                priority
                style={{ width: "auto", height: "auto" }}
              />
              <div className="min-w-0">
                <div className="text-[13px] sm:text-[14px] font-semibold text-white leading-tight truncate">
                  {published ? "Published" : editId ? "Edit prompt" : "Publish prompt"}
                </div>
                <div className="flex flex-wrap items-center gap-1.5 sm:gap-2 text-[10px] sm:text-[11px] text-white/45 min-w-0">
                  <span className="shrink-0">Posting as</span>
                  <span className="min-w-0 truncate">{ownerName}</span>
                  {profile?.is_verified_creator ? (
                    <VerifiedCreatorBadge variant="mark" size="xs" className="shrink-0" />
                  ) : null}
                  <span className="truncate">@{ownerHandle}</span>
                </div>
              </div>
            </div>

            <div className="mt-2.5 flex items-center gap-2 sm:mt-0">
              {headerCta}
              <button
                onClick={published ? undefined : closeNow}
                className={cx(
                  "grid h-9 w-9 shrink-0 place-items-center rounded-full border border-white/12 bg-white/5 text-white/80 hover:bg-white/10",
                  published && "opacity-60 cursor-not-allowed",
                )}
                aria-label="Close"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Body */}
          <div className="flex min-h-0 flex-1 flex-col gap-0 overflow-hidden md:grid md:grid-cols-12">
            {/* Left: Stepper */}
            <div className="shrink-0 border-b border-white/10 px-3 py-2.5 sm:px-5 sm:py-4 md:col-span-4 md:border-b-0 md:border-r md:p-5">
              <div className="flex items-center justify-between">
                <div className="text-[11px] font-semibold text-white/80">Progress</div>
                <div className="text-[10px] text-white/45">
                  Step {Math.min(step + 1, STEPS.length)}/{STEPS.length}
                </div>
              </div>

              <div className="mt-3 grid grid-cols-5 gap-2 md:hidden">
                {STEPS.map((s, i) => {
                  const canClick =
                    i <= step ||
                    (() => {
                      for (let k = 0; k < i; k++) {
                        if (!stepCanAdvance(k)) return false;
                      }
                      return true;
                    })();

                  return (
                    <MobileStepPill
                      key={s.key}
                      title={s.title}
                      active={activeVisibleStep === s.key}
                      done={!!completed[s.key]}
                      icon={s.icon}
                      canClick={(showAllMobileSections || canClick) && !busy && !published}
                      onClick={() =>
                        showAllMobileSections ? scrollToPromptSection(s.key) : goToStep(i)
                      }
                    />
                  );
                })}
              </div>

              <div className="mt-3 hidden space-y-1.5 md:block">
                {STEPS.map((s, i) => {
                  const canClick =
                    i <= step ||
                    (() => {
                      for (let k = 0; k < i; k++) {
                        if (!stepCanAdvance(k)) return false;
                      }
                      return true;
                    })();

                  return (
                    <StepDot
                      key={s.key}
                      index={i}
                      title={s.title}
                      desc={s.desc}
                      active={i === step}
                      done={!!completed[s.key]}
                      icon={s.icon}
                      canClick={canClick && !busy && !published}
                      onClick={() => goToStep(i)}
                    />
                  );
                })}
              </div>

              {err ? (
                <div className="mt-4 rounded-2xl border border-red-500/30 bg-red-500/10 p-3 text-[12px] text-red-200">
                  <div className="flex items-start gap-2">
                    <AlertTriangle className="h-4 w-4 mt-0.5" />
                    <div>{err}</div>
                  </div>
                </div>
              ) : null}

              {!published ? (
                <div className="mt-4 hidden gap-2 md:flex">
                  <button
                    type="button"
                    onClick={goPrev}
                    disabled={step === 0 || busy}
                    className={cx(
                      "h-10 flex-1 inline-flex items-center justify-center gap-2 rounded-2xl border border-white/12 bg-white/5 px-3 text-[12px] font-semibold text-white/85 hover:bg-white/10",
                      (step === 0 || busy) && "opacity-60 cursor-not-allowed",
                    )}
                  >
                    <ChevronLeft className="h-4 w-4" />
                    Back
                  </button>

                  <button
                    type="button"
                    onClick={stepKey === "review" ? handlePublish : goNext}
                    disabled={busy || (stepKey === "review" ? !canPublish : !stepCanAdvance(step))}
                    className={cx(
                      "h-10 flex-1 inline-flex items-center justify-center gap-2 rounded-2xl px-3 text-[12px] font-semibold",
                      "bg-white text-black hover:bg-white/90",
                      (stepKey === "review" ? !canPublish : !stepCanAdvance(step)) &&
                        "opacity-60 cursor-not-allowed",
                    )}
                  >
                    {stepKey === "review" ? (
                      <>
                        <Sparkles className="h-4 w-4" />
                        {editId ? "Update" : "Publish"}
                      </>
                    ) : (
                      <>
                        Next
                        <ChevronRight className="h-4 w-4" />
                      </>
                    )}
                  </button>
                </div>
              ) : null}
            </div>

            {/* Right: Content */}
            <div
              ref={contentScrollRef}
              className="min-h-0 flex-1 overflow-x-hidden overflow-y-auto p-4 sm:p-5 md:col-span-8"
            >
              {!published ? (
                <>
                  {showAllMobileSections || stepKey === "details" ? (
                    <div
                      ref={(node) => {
                        sectionRefs.current.details = node;
                      }}
                      data-section="details"
                      className="space-y-4"
                    >
                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        {showAllMobileSections ? (
                          <div className="mb-4 flex items-center gap-3 md:hidden">
                            <div className="grid h-10 w-10 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">
                              <FileText className="h-4 w-4" />
                            </div>
                            <div>
                              <div className="text-[12px] font-semibold text-white">Basics</div>
                              <div className="text-[11px] text-white/45">
                                Core listing details and code.
                              </div>
                            </div>
                          </div>
                        ) : null}
                        <div className="text-[12px] font-semibold text-white/85">Basic details</div>
                        <div className="text-[11px] text-white/50 mt-1">
                          Make it clear and searchable.
                        </div>

                        <div className="mt-4">
                          <div className="text-[12px] font-semibold text-white/80">Title</div>
                          <input
                            value={title}
                            onChange={(e) => {
                              setTitle(e.target.value);
                              const next = e.target.value;
                              if (!edgazeCode) setEdgazeCode(baseCodeFromTitle(next));
                            }}
                            className="mt-2 w-full rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-[13px] text-white outline-none focus:border-cyan-400/40"
                            placeholder="Give it a strong title"
                          />
                        </div>

                        <div className="mt-4">
                          <div className="text-[12px] font-semibold text-white/80">Description</div>
                          <textarea
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            className="mt-2 w-full min-h-[110px] rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-[13px] text-white outline-none focus:border-cyan-400/40"
                            placeholder="What does this prompt do?"
                          />
                        </div>

                        <div className="mt-4 grid grid-cols-12 gap-3">
                          <div className="col-span-12 lg:col-span-7">
                            <div className="text-[12px] font-semibold text-white/80">
                              Edgaze code
                            </div>
                            <input
                              value={edgazeCode}
                              onChange={(e) => setEdgazeCode(e.target.value)}
                              className="mt-2 w-full rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-[13px] text-white outline-none focus:border-cyan-400/40"
                              placeholder="e.g. essay-wizard"
                            />
                            <div className="mt-2 text-[11px] text-white/45">
                              Link format: <span className="text-white/70">/p/{ownerHandle}/</span>
                              <span className="text-white/70">
                                {normalizeEdgazeCode(edgazeCode) || "your-code"}
                              </span>
                            </div>
                          </div>

                          <div className="col-span-12 lg:col-span-5">
                            <div className="text-[12px] font-semibold text-white/80">
                              Availability
                            </div>
                            <div
                              className={cx(
                                "mt-2 rounded-2xl border px-4 py-3 text-[12px] font-semibold",
                                codeStatus === "available"
                                  ? "border-cyan-400/25 bg-cyan-400/10 text-cyan-200"
                                  : codeStatus === "taken"
                                    ? "border-red-500/25 bg-red-500/10 text-red-200"
                                    : codeStatus === "invalid"
                                      ? "border-amber-500/25 bg-amber-500/10 text-amber-200"
                                      : "border-white/10 bg-black/35 text-white/70",
                              )}
                            >
                              {codeStatus === "checking" ? "Checking…" : codeMsg || "—"}
                            </div>
                            <div className="mt-2 text-[11px] text-white/45">
                              Codes are lowercase, up to 32 chars.
                            </div>
                          </div>
                        </div>

                        <div className="mt-4">
                          <div className="text-[12px] font-semibold text-white/80">Tags</div>
                          <input
                            value={tagsInput}
                            onChange={(e) => setTagsInput(e.target.value)}
                            className="mt-2 w-full rounded-2xl border border-white/10 bg-black/35 px-4 py-3 text-[13px] text-white outline-none focus:border-cyan-400/40"
                            placeholder="comma separated (ai, writing, study)"
                          />
                        </div>
                      </div>

                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        <div className="text-[12px] font-semibold text-white/85">Readiness</div>
                        <div className="mt-3 grid grid-cols-12 gap-3">
                          {[
                            { ok: safeTitle.length > 0, label: "Title" },
                            { ok: safeDescription.length > 0, label: "Description" },
                            { ok: promptText.trim().length > 0, label: "Prompt text" },
                            { ok: hasValidPlaceholders, label: "Placeholders" },
                            { ok: codeStatus === "available", label: "Code available" },
                          ].map((i) => (
                            <div key={i.label} className="col-span-12 sm:col-span-6">
                              <div
                                className={cx(
                                  "flex items-center justify-between rounded-2xl border px-4 py-3",
                                  i.ok
                                    ? "border-cyan-400/20 bg-cyan-400/10"
                                    : "border-white/10 bg-black/35",
                                )}
                              >
                                <div className="text-[12px] font-semibold text-white">
                                  {i.label}
                                </div>
                                {i.ok ? (
                                  <CheckCircle2 className="h-4 w-4 text-cyan-200" />
                                ) : (
                                  <div className="text-[11px] text-white/45">—</div>
                                )}
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  ) : null}

                  {showAllMobileSections || stepKey === "pricing" ? (
                    <div
                      ref={(node) => {
                        sectionRefs.current.pricing = node;
                      }}
                      data-section="pricing"
                      className="space-y-4"
                    >
                      {!canReceivePayments && (
                        <PayoutSystemCard
                          variant="prompt"
                          showCheckbox={monetisationMode === "paywall"}
                          acceptedCreatorTerms={acceptedCreatorTerms}
                          onAcceptedChange={setAcceptedCreatorTerms}
                        />
                      )}
                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        {showAllMobileSections ? (
                          <div className="mb-4 flex items-center gap-3 md:hidden">
                            <div className="grid h-10 w-10 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">
                              <BadgeDollarSign className="h-4 w-4" />
                            </div>
                            <div>
                              <div className="text-[12px] font-semibold text-white">Pricing</div>
                              <div className="text-[11px] text-white/45">
                                Set free or paid access.
                              </div>
                            </div>
                          </div>
                        ) : null}
                        <div className="text-[12px] font-semibold text-white/85">Pricing</div>
                        <div className="text-[11px] text-white/50 mt-1">
                          Choose Free or set a price ($3–$50 for prompts).
                        </div>

                        <div className="mt-4 grid grid-cols-12 gap-3">
                          <button
                            type="button"
                            onClick={() => setMonetisationMode("free")}
                            className={cx(
                              "col-span-12 md:col-span-6 rounded-2xl border p-4 text-left transition-colors",
                              monetisationMode === "free"
                                ? "border-cyan-400/25 bg-cyan-400/10"
                                : "border-white/10 bg-white/[0.02] hover:bg-white/[0.04]",
                            )}
                          >
                            <div className="flex items-center justify-between">
                              <div className="text-[12px] font-semibold text-white">Free</div>
                              {monetisationMode === "free" ? (
                                <CheckCircle2 className="h-4 w-4 text-cyan-200" />
                              ) : null}
                            </div>
                            <div className="text-[11px] text-white/55 mt-1">
                              Everyone can use it.
                            </div>
                          </button>

                          <button
                            type="button"
                            onClick={() => setMonetisationMode("paywall")}
                            className={cx(
                              "col-span-12 md:col-span-6 rounded-2xl border p-4 text-left transition-colors",
                              monetisationMode === "paywall"
                                ? "border-cyan-400/25 bg-cyan-400/10"
                                : "border-white/10 bg-white/[0.02] hover:bg-white/[0.04]",
                            )}
                          >
                            <div className="flex items-center justify-between">
                              <div className="text-[12px] font-semibold text-white">Paywall</div>
                              {monetisationMode === "paywall" ? (
                                <CheckCircle2 className="h-4 w-4 text-cyan-200" />
                              ) : null}
                            </div>
                            <div className="text-[11px] text-white/55 mt-1">
                              Charge $3–$50 per purchase.
                            </div>
                          </button>
                        </div>

                        {monetisationMode === "paywall" && (
                          <div className="mt-4 rounded-2xl border border-white/10 bg-black/35 p-4">
                            <div className="text-[12px] font-semibold text-white/90 mb-2">
                              Price (USD)
                            </div>
                            <input
                              type="number"
                              min={MIN_TRANSACTION_USD}
                              max={PROMPT_MAX_USD}
                              step="0.99"
                              value={priceUsd}
                              onChange={(e) => setPriceUsd(e.target.value)}
                              className="w-full rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-[14px] text-white placeholder-white/40 focus:border-cyan-400/50 focus:ring-1 focus:ring-cyan-400/30 focus:outline-none"
                              placeholder="3.99"
                            />
                            {priceValidation.error && (
                              <p className="mt-2 text-[11px] text-amber-400">
                                {priceValidation.error}
                              </p>
                            )}
                            <p className="mt-2 text-[11px] text-white/45">
                              Minimum $3, maximum $50 for prompts.
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  ) : null}

                  {showAllMobileSections || stepKey === "media" ? (
                    <div
                      ref={(node) => {
                        sectionRefs.current.media = node;
                      }}
                      data-section="media"
                      className="space-y-4"
                    >
                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        {showAllMobileSections ? (
                          <div className="mb-4 flex items-center gap-3 md:hidden">
                            <div className="grid h-10 w-10 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">
                              <Images className="h-4 w-4" />
                            </div>
                            <div>
                              <div className="text-[12px] font-semibold text-white">Media</div>
                              <div className="text-[11px] text-white/45">
                                Thumbnail and demo assets.
                              </div>
                            </div>
                          </div>
                        ) : null}
                        <div className="flex items-center justify-between gap-3">
                          <div>
                            <div className="text-[12px] font-semibold text-white/85">Thumbnail</div>
                            <div className="text-[11px] text-white/50 mt-1">
                              Upload, pick from assets, or use auto-generated.
                            </div>
                          </div>
                          <button
                            type="button"
                            onClick={() => setAssetPickerOpen(true)}
                            className="inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/5 px-4 py-2 text-[12px] text-white/85 hover:bg-white/10"
                          >
                            <Upload className="h-4 w-4" />
                            Pick from assets
                          </button>
                        </div>

                        <div className="mt-4 grid grid-cols-12 gap-4">
                          <div className="col-span-12 lg:col-span-7">
                            <div className="rounded-3xl border border-white/10 bg-black/35 p-4">
                              <div className="flex items-center justify-between">
                                <div className="text-[11px] font-semibold text-white/70">
                                  {meta?.thumbnailUrl
                                    ? "Selected from assets"
                                    : thumbnailFile
                                      ? "Uploaded"
                                      : "Auto"}
                                </div>
                                <button
                                  type="button"
                                  onClick={generateAutoThumbnail}
                                  disabled={
                                    autoThumbBusy || !!meta?.thumbnailUrl || !!thumbnailFile
                                  }
                                  className={cx(
                                    "inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/5 px-3 py-1.5 text-[11px] text-white/80 hover:bg-white/10",
                                    (autoThumbBusy || !!meta?.thumbnailUrl || !!thumbnailFile) &&
                                      "opacity-60 cursor-not-allowed",
                                  )}
                                >
                                  <RotateCcw className="h-3.5 w-3.5" />
                                  Regenerate
                                </button>
                              </div>

                              <div className="relative mt-3 aspect-[16/10] overflow-hidden rounded-2xl border border-white/10 bg-white/[0.02]">
                                {safeThumbnailSrc ? (
                                  <Image
                                    src={safeThumbnailSrc}
                                    alt="Thumbnail"
                                    fill
                                    unoptimized
                                    sizes="(max-width: 1024px) 100vw, 50vw"
                                    className="h-full w-full object-cover"
                                  />
                                ) : safeUploadedThumbnailSrc ? (
                                  <Image
                                    src={safeUploadedThumbnailSrc}
                                    alt="Thumbnail upload"
                                    fill
                                    unoptimized
                                    sizes="(max-width: 1024px) 100vw, 50vw"
                                    className="h-full w-full object-cover"
                                  />
                                ) : safeAutoThumbnailSrc ? (
                                  <Image
                                    src={safeAutoThumbnailSrc}
                                    alt="Auto thumbnail"
                                    fill
                                    unoptimized
                                    sizes="(max-width: 1024px) 100vw, 50vw"
                                    className="h-full w-full object-cover"
                                  />
                                ) : (
                                  <div className="h-full w-full grid place-items-center text-[11px] text-white/55">
                                    {autoThumbBusy ? "Generating…" : "No thumbnail"}
                                  </div>
                                )}
                              </div>

                              <div className="mt-3 text-[11px] text-white/45">
                                Auto thumbnail stays in sync with your prompt unless you upload/pick
                                one.
                              </div>
                            </div>
                          </div>

                          <div className="col-span-12 lg:col-span-5">
                            <div className="rounded-3xl border border-white/10 bg-black/35 p-4">
                              <div className="text-[11px] font-semibold text-white/70">
                                Upload a thumbnail
                              </div>
                              <input
                                type="file"
                                accept="image/*"
                                className="mt-3 block w-full text-[12px] text-white/70 file:mr-3 file:rounded-full file:border-0 file:bg-white file:px-4 file:py-2 file:text-[12px] file:font-semibold file:text-black hover:file:bg-white/90"
                                onChange={(e) => {
                                  const f = e.target.files?.[0] || null;
                                  setThumbnailFile(f);
                                  if (f) {
                                    // if user uploads, clear asset-selected thumb (avoid ambiguity)
                                    if (meta?.thumbnailUrl)
                                      onMetaChange?.({
                                        ...meta,
                                        thumbnailUrl: "",
                                        thumbnailAutoGenerated: false,
                                      });
                                  }
                                }}
                              />
                              <button
                                type="button"
                                onClick={() => {
                                  setThumbnailFile(null);
                                }}
                                className={cx(
                                  "mt-3 inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/5 px-3 py-1.5 text-[11px] text-white/80 hover:bg-white/10",
                                  !thumbnailFile && "opacity-60 cursor-not-allowed",
                                )}
                                disabled={!thumbnailFile}
                              >
                                <RotateCcw className="h-3.5 w-3.5" />
                                Remove upload
                              </button>

                              <div className="mt-3 text-[11px] text-white/45">
                                Upload overrides auto. Asset selection overrides both.
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        <div className="flex items-center justify-between">
                          <div>
                            <div className="text-[12px] font-semibold text-white/85">
                              Demo images
                            </div>
                            <div className="text-[11px] text-white/50 mt-1">
                              Optional. Add up to 6 example outputs.
                            </div>
                          </div>
                          <div className="text-[11px] font-semibold rounded-full border border-white/10 bg-white/[0.03] px-3 py-1.5 text-white/70">
                            {demoCount}/6
                          </div>
                        </div>

                        <div className="mt-4 grid grid-cols-12 gap-3">
                          {new Array(6).fill(null).map((_, i) => (
                            <div
                              key={i}
                              className="col-span-12 sm:col-span-6 lg:col-span-4 rounded-2xl border border-white/10 bg-black/35 p-3"
                            >
                              <div className="flex items-center justify-between">
                                <div className="text-[11px] font-semibold text-white/70">
                                  Slot {i + 1}
                                </div>
                                {demoFiles[i] ? (
                                  <CheckCircle2 className="h-4 w-4 text-cyan-200" />
                                ) : null}
                              </div>

                              <input
                                type="file"
                                accept="image/*"
                                className="mt-2 block w-full text-[12px] text-white/70 file:mr-3 file:rounded-full file:border-0 file:bg-white file:px-3 file:py-1.5 file:text-[12px] file:font-semibold file:text-black hover:file:bg-white/90"
                                onChange={(e) => {
                                  const f = e.target.files?.[0] || null;
                                  setDemoFiles((prev) => {
                                    const copy = [...prev];
                                    copy[i] = f;
                                    return copy;
                                  });
                                }}
                              />

                              {demoFiles[i] ? (
                                <div className="mt-2 text-[11px] text-white/45 truncate">
                                  {demoFiles[i]?.name}
                                </div>
                              ) : (
                                <div className="mt-2 text-[11px] text-white/45">
                                  Upload an example output.
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  ) : null}

                  {showAllMobileSections || stepKey === "visibility" ? (
                    <div
                      ref={(node) => {
                        sectionRefs.current.visibility = node;
                      }}
                      data-section="visibility"
                      className="space-y-4"
                    >
                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        {showAllMobileSections ? (
                          <div className="mb-4 flex items-center gap-3 md:hidden">
                            <div className="grid h-10 w-10 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">
                              <Lock className="h-4 w-4" />
                            </div>
                            <div>
                              <div className="text-[12px] font-semibold text-white">Visibility</div>
                              <div className="text-[11px] text-white/45">
                                Control how it appears publicly.
                              </div>
                            </div>
                          </div>
                        ) : null}
                        <div className="text-[12px] font-semibold text-white/85">Visibility</div>
                        <div className="text-[11px] text-white/50 mt-1">
                          Choose who can see your prompt.
                        </div>

                        <div className="mt-4 grid grid-cols-12 gap-3">
                          {(["public", "unlisted", "private"] as Visibility[]).map((v) => {
                            const disabled = v !== "public";
                            return (
                              <button
                                key={v}
                                type="button"
                                disabled={disabled}
                                onClick={() => setVisibility(v)}
                                className={cx(
                                  "col-span-12 md:col-span-4 rounded-2xl border p-4 text-left capitalize transition-colors",
                                  disabled
                                    ? "border-white/10 bg-white/[0.02] opacity-70 cursor-not-allowed"
                                    : visibility === v
                                      ? "border-cyan-400/25 bg-cyan-400/10"
                                      : "border-white/10 bg-white/[0.02] hover:bg-white/[0.04]",
                                )}
                              >
                                <div className="flex items-center justify-between">
                                  <div className="text-[12px] font-semibold text-white">{v}</div>
                                  {disabled ? (
                                    <span className="text-[10px] rounded-full border border-white/10 bg-white/[0.05] px-2 py-1 text-white/70">
                                      Coming soon
                                    </span>
                                  ) : (
                                    <CheckCircle2 className="h-4 w-4 text-cyan-200" />
                                  )}
                                </div>
                                <div className="text-[11px] text-white/55 mt-1">
                                  {v === "public"
                                    ? "Visible to everyone."
                                    : v === "unlisted"
                                      ? "Only via link."
                                      : "Only you."}
                                </div>
                              </button>
                            );
                          })}
                        </div>
                      </div>
                    </div>
                  ) : null}

                  {showAllMobileSections || stepKey === "review" ? (
                    <div
                      ref={(node) => {
                        sectionRefs.current.review = node;
                      }}
                      data-section="review"
                      className="space-y-4"
                    >
                      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
                        {showAllMobileSections ? (
                          <div className="mb-4 flex items-center gap-3 md:hidden">
                            <div className="grid h-10 w-10 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/10 text-cyan-100">
                              <Eye className="h-4 w-4" />
                            </div>
                            <div>
                              <div className="text-[12px] font-semibold text-white">Review</div>
                              <div className="text-[11px] text-white/45">
                                Final pass before you publish.
                              </div>
                            </div>
                          </div>
                        ) : null}
                        <div className="text-[12px] font-semibold text-white/85">Review</div>
                        <div className="text-[11px] text-white/50 mt-1">
                          Confirm everything before publishing.
                        </div>

                        <div className="mt-4 grid grid-cols-12 gap-3">
                          <div className="col-span-12 lg:col-span-7 rounded-3xl border border-white/10 bg-black/35 p-4">
                            <div className="text-[11px] font-semibold text-white/70">Title</div>
                            <div className="mt-1 text-[14px] font-semibold text-white">
                              {safeTitle || "—"}
                            </div>

                            <div className="mt-4 text-[11px] font-semibold text-white/70">
                              Description
                            </div>
                            <div className="mt-1 text-[12px] text-white/75 whitespace-pre-wrap">
                              {safeDescription || "—"}
                            </div>

                            <div className="mt-4 grid grid-cols-12 gap-3">
                              <div className="col-span-12 sm:col-span-6">
                                <div className="text-[11px] font-semibold text-white/70">
                                  Edgaze code
                                </div>
                                <div className="mt-1 text-[12px] text-white/80">
                                  {normalizeEdgazeCode(edgazeCode) || "—"}
                                </div>
                              </div>
                              <div className="col-span-12 sm:col-span-6">
                                <div className="text-[11px] font-semibold text-white/70">
                                  Visibility
                                </div>
                                <div className="mt-1 text-[12px] text-white/80">Public</div>
                              </div>
                            </div>

                            <div className="mt-4 text-[11px] font-semibold text-white/70">Tags</div>
                            <div className="mt-2 flex flex-wrap gap-2">
                              {safeArr(tagsInput).length ? (
                                safeArr(tagsInput)
                                  .slice(0, 10)
                                  .map((t) => (
                                    <span
                                      key={t}
                                      className="rounded-full border border-white/10 bg-white/[0.04] px-3 py-1 text-[11px] text-white/80"
                                    >
                                      {t}
                                    </span>
                                  ))
                              ) : (
                                <span className="text-[11px] text-white/45">No tags</span>
                              )}
                            </div>
                          </div>

                          <div className="col-span-12 lg:col-span-5 rounded-3xl border border-white/10 bg-black/35 p-4">
                            <div className="text-[11px] font-semibold text-white/70">
                              Prompt preview (blurred)
                            </div>
                            <div className="mt-2 rounded-2xl border border-white/10 bg-black/40 p-3 overflow-hidden relative">
                              <div
                                className="text-[12px] leading-relaxed text-white/85 select-none whitespace-pre-wrap"
                                style={{
                                  filter: "blur(7px)",
                                  opacity: 0.9,
                                  transform: "translateZ(0)",
                                  userSelect: "none",
                                }}
                              >
                                {makePromptPreviewForUI(promptText) || "—"}
                              </div>
                              {/* veil + subtle noise to make it barely readable */}
                              <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-black/25 via-black/15 to-black/30" />
                              <div className="pointer-events-none absolute inset-0 opacity-40 [background-image:radial-gradient(circle_at_20%_20%,rgba(255,255,255,0.08),transparent_40%),radial-gradient(circle_at_80%_60%,rgba(255,255,255,0.06),transparent_45%)]" />
                              <div className="pointer-events-none absolute inset-0 ring-1 ring-white/10 rounded-2xl" />
                            </div>

                            <div className="mt-3 text-[11px] text-white/50">
                              Full prompt is saved. This preview is just for review UI.
                            </div>

                            <div className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-4">
                              <div className="text-[11px] font-semibold text-white/80">
                                By publishing
                              </div>
                              <div className="mt-1 text-[11px] text-white/50">
                                You agree to our{" "}
                                <a
                                  className="text-white/80 hover:text-white underline underline-offset-4"
                                  href="/docs/terms-of-service"
                                  target="_blank"
                                  rel="noopener noreferrer"
                                >
                                  Terms of Service
                                </a>
                                ,{" "}
                                <a
                                  className="text-white/80 hover:text-white underline underline-offset-4"
                                  href="/docs/privacy-policy"
                                  target="_blank"
                                  rel="noopener noreferrer"
                                >
                                  Privacy Policy
                                </a>
                                ,{" "}
                                <a
                                  className="text-white/80 hover:text-white underline underline-offset-4"
                                  href="/docs/creator-terms"
                                  target="_blank"
                                  rel="noopener noreferrer"
                                >
                                  Creator Terms
                                </a>
                                ,{" "}
                                <a
                                  className="text-white/80 hover:text-white underline underline-offset-4"
                                  href="/docs/community-guidelines"
                                  target="_blank"
                                  rel="noopener noreferrer"
                                >
                                  Community Guidelines
                                </a>
                                , and{" "}
                                <a
                                  className="text-white/80 hover:text-white underline underline-offset-4"
                                  href="/docs/refund-policy"
                                  target="_blank"
                                  rel="noopener noreferrer"
                                >
                                  Refund Policy
                                </a>
                                .
                              </div>
                            </div>
                          </div>
                        </div>

                        <div className="mt-4 rounded-2xl border border-white/10 bg-black/35 p-4">
                          <div className="flex items-center justify-between">
                            <div className="text-[11px] font-semibold text-white/70">Media</div>
                            <div className="text-[11px] font-semibold rounded-full border border-cyan-400/25 bg-cyan-400/10 px-3 py-1.5 text-cyan-200">
                              Thumbnail{" "}
                              {demoCount > 0 ? `+ ${demoCount} demo(s)` : "(demos optional)"}
                            </div>
                          </div>
                          <div className="mt-1 text-[11px] text-white/50">
                            Demo images are optional.
                          </div>
                        </div>
                      </div>
                    </div>
                  ) : null}
                </>
              ) : (
                // Published view (keeps old functionality)
                <div className="grid grid-cols-12 gap-4">
                  <div className="col-span-12 rounded-3xl border border-white/10 bg-white/[0.03] p-4 sm:p-5">
                    <div className="flex items-center gap-2 text-white">
                      <CheckCircle2 className="h-5 w-5 text-cyan-300" />
                      <div className="text-[14px] font-semibold">Published</div>
                    </div>

                    <div className="mt-4 grid grid-cols-12 gap-4">
                      <div className="col-span-12 lg:col-span-7 rounded-3xl border border-white/10 bg-black/35 p-4 sm:p-5">
                        <div className="text-[11px] font-semibold text-white/70">Edgaze code</div>
                        <div className="mt-2 break-words text-[28px] font-semibold leading-none tracking-tight text-white sm:text-[34px]">
                          {publishedCode}
                        </div>

                        <div className="mt-4 text-[11px] font-semibold text-white/70">
                          Share link
                        </div>
                        <div className="mt-2 flex flex-col gap-2 sm:flex-row sm:items-center">
                          <div className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-black/40 px-3 py-2 text-[12px] text-white/80 overflow-hidden">
                            <span className="inline-flex items-center gap-2">
                              <LinkIcon className="h-4 w-4 shrink-0 text-white/55" />
                              <span className="min-w-0 truncate">{publishedUrl}</span>
                            </span>
                          </div>
                          <button
                            onClick={async () => {
                              await copyToClipboard(publishedUrl);
                            }}
                            className="inline-flex h-10 w-full items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-3 text-[12px] font-semibold text-white/90 hover:bg-white/10 sm:w-auto"
                          >
                            <span className="inline-flex items-center gap-2">
                              <Copy className="h-4 w-4" />
                              Copy
                            </span>
                          </button>
                        </div>

                        <div className="mt-4 text-[11px] text-white/45">
                          Published as{" "}
                          {monetisationMode === "free" ? (
                            <span className="font-semibold text-emerald-400">Free</span>
                          ) : (
                            <span className="font-semibold text-white/90">
                              ${Number(priceUsd || 0).toFixed(2)}
                            </span>
                          )}
                        </div>
                      </div>

                      <div className="col-span-12 lg:col-span-5 rounded-3xl border border-white/10 bg-black/35 p-4 sm:p-5">
                        <div className="flex items-center justify-between">
                          <div className="text-[11px] font-semibold text-white/70">QR</div>
                          <button
                            type="button"
                            onClick={async () => {
                              setQrBusy(true);
                              try {
                                const qr = await withTimeout(
                                  qrWithCenteredLogoDataUrl(publishedUrl),
                                  9000,
                                  "QR render",
                                );
                                setQrDataUrl(qr);
                              } finally {
                                setQrBusy(false);
                              }
                            }}
                            className="inline-flex items-center gap-2 rounded-full border border-white/12 bg-white/5 px-3 py-1.5 text-[11px] text-white/80 hover:bg-white/10"
                          >
                            <RotateCcw className="h-3.5 w-3.5" />
                            Regenerate
                          </button>
                        </div>

                        <div className="mt-3 grid place-items-center rounded-3xl border border-white/10 bg-black/40 p-3">
                          <div className="grid aspect-square w-full max-w-[220px] place-items-center overflow-hidden rounded-2xl bg-white/[0.03]">
                            {qrBusy ? (
                              <div className="inline-flex items-center gap-2 text-[12px] text-white/60">
                                <Loader2 className="h-4 w-4 animate-spin" />
                                Generating…
                              </div>
                            ) : qrDataUrl ? (
                              <img
                                src={qrDataUrl}
                                alt="Edgaze QR"
                                className="h-full w-full object-cover"
                              />
                            ) : (
                              <div className="text-[12px] text-white/55">
                                {qrErr || "QR unavailable"}
                              </div>
                            )}
                          </div>
                        </div>

                        <div className="mt-3 flex gap-2">
                          <button
                            type="button"
                            disabled={!qrDataUrl}
                            onClick={() =>
                              qrDataUrl
                                ? downloadDataUrl(
                                    qrDataUrl,
                                    `edgaze-qr-${publishedCode || "prompt"}.png`,
                                  )
                                : null
                            }
                            className={cx(
                              "h-10 flex-1 rounded-2xl border border-white/10 bg-white/5 px-3 text-[12px] font-semibold text-white/90 hover:bg-white/10",
                              !qrDataUrl && "opacity-60 cursor-not-allowed",
                            )}
                          >
                            <span className="inline-flex items-center gap-2 justify-center w-full">
                              <Download className="h-4 w-4" />
                              Download
                            </span>
                          </button>
                        </div>
                      </div>
                    </div>

                    <div className="mt-4 text-[11px] text-white/45">
                      You agreed to{" "}
                      <a
                        href="/docs/terms-of-service"
                        className="text-white/60 hover:text-white underline underline-offset-4"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Terms
                      </a>
                      ,{" "}
                      <a
                        href="/docs/privacy-policy"
                        className="text-white/60 hover:text-white underline underline-offset-4"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Privacy Policy
                      </a>
                      ,{" "}
                      <a
                        href="/docs/creator-terms"
                        className="text-white/60 hover:text-white underline underline-offset-4"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Creator Terms
                      </a>
                      ,{" "}
                      <a
                        href="/docs/community-guidelines"
                        className="text-white/60 hover:text-white underline underline-offset-4"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Community Guidelines
                      </a>
                      , and{" "}
                      <a
                        href="/docs/refund-policy"
                        className="text-white/60 hover:text-white underline underline-offset-4"
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        Refund Policy
                      </a>{" "}
                      at publish time.
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Asset picker */}
          {assetPickerOpen ? (
            <AssetPickerModal
              onClose={() => setAssetPickerOpen(false)}
              onPick={(asset: any) => {
                const url = asset?.url || "";
                if (url) {
                  onMetaChange?.({ ...meta, thumbnailUrl: url, thumbnailAutoGenerated: false });
                  // if picking asset, clear upload to avoid confusion
                  setThumbnailFile(null);
                }
                setAssetPickerOpen(false);
              }}
            />
          ) : null}
        </div>
      </div>
    </div>
  );

  if (typeof document === "undefined") return null;
  return createPortal(shell, document.body);
}
